### PR TITLE
Add metrics for tracking live servers

### PR DESCRIPTION
**Pull request by iainlane**
Problem
=======

Occasionally we've noticed that the autoscalers know about instances that the VM providers (e.g. GCP or AWS) don't or vice versa. I'd like to expose the servers from the autoscaler and then we can correlate both sides to have an alert when they get out of sync.

I'd like a bit of discussion between ourselves first before proposing upstream. This is probably something that we shouldn't fork on, since it'll be annoying to have to change the implementation if what we do downstream doesn't fly.

Proposal
========

Add a new metric `drone_server_known_instance` with a label for the instance name.

This should allow us to correlate the servers that drone thinks it knows about with those that GCP has.

Technically this has unbounded cardinality but I think it's okay in reality since the metric is deleted when a server goes away and we'll really only be doing instant ("give me the values now") queries on this.

Alternatives
============

`drone_server_count`
--------------------

There is already `drone_server_count` which could gain some labels.

  1. I'm not sure if that counts as an "API break", could it make existing queries stop working? Actually don't know the answer to that one.
  2. Would cardinality be more of a problem there, is that a relevant concern?

Doing something with logs
-------------------------

For completeness-

We could make sure to log nice clear messages when servers turn up and leave.

  1. It'll be annoying to correlate if done manually
  2. Unless we use a recording rule somehow
  3. Which then has the same problems as the others, so why not use a metric directly?

### CODE REVIEW

**Comment by iainlane** [comment]
I wanted to add @grafana/cloud-platform as a reviewer but the team isn't an option. Could someone help? IIRC they need to be added to the repo in its settings somewhere. (Perhaps that doesn't work for forks?)

**Comment by julienduchesne** [comment]
> I wanted to add @grafana/cloud-platform as a reviewer but the team isn't an option. Could someone help? IIRC they need to be added to the repo in its settings somewhere. (Perhaps that doesn't work for forks?)

Done!

**Review by julienduchesne — APPROVED** [review]
Seems like a good idea to me!

**Comment by iainlane** [comment]
Just noticed this on my PR list. I've not done anything with this and I forgot the context - so I'll close.

**Pull request closed without merging**
